language: node_js

node_js:
  - 'node'
  - '10'

script:
  - npm test
  - npm run lint

branches:
  only:
  - master

install:
  - npm uninstall typescript --no-save
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1